import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
const ThemeToggle = dynamic(() => import("../components/ThemeToggle"), {
  ssr: false,
});
import dynamic from "next/dynamic";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.first_row}>
          <div className={styles.name_time}>
            <h4>Dl 2R 5438</h4>
            <h4>15:30</h4>
          </div>
          <div className={styles.date_togg}>
            <h4>Friday 14 Oct 2022</h4>
            <button>Notes</button>
            <ThemeToggle />
          </div>
        </div>
        <h1 className={styles.heading}>oidcoidio</h1>
      </main>
    </div>
  );
}
